### ISSUE TITLE
Audio levels need normalization

### ISSUE THREAD

**Issue by baodrate** [WhoTheFlower/Steam-Deck-UI-Components#1]
I assume the files are ripped straight from the games? I'm thinking of these two files in particular (they're currently identical): `deck_ui_into_game_detail.wav` and `deck_ui_side_menu_fly_in.wav`. The volume for that file is much higher than all the other sounds so it **blasts** your headphones. It would probably make sense to normalize the sounds so they match the default steamOS ones.

I can do it if you'd accept the PR

**Comment by WhoTheFlower** [comment]
I don't remember how I got the files but I'll look into it as soon as possible and provide an update to it, I rushed getting out the sound pack along with the music packs

**Comment by WhoTheFlower** [comment]
Audio levels should be normalized for the next update, thanks for your support
